### ISSUE TITLE
Issues in DoctrineDbal.php

### ISSUE THREAD

**Issue by borb** [wethersherbs/pineapple#15]
From code review:

> Remove ‘var’ before properties and add visibility
> Remove _ before the properties _BCsequence and $_db on lines 124 and 591 as they should not be prefixed
> CamelCase variable names
> ln 84 DBALConnection incorrect var assignment therefore rest of file highlights incorrectly missing functions
> ln 108 $transaction_opcount can be private, tests can use reflection
> ln 126 unnecessary constructor and the doc block is incorrect
> ln 191 incorrect doc block also argument array $dsn missing
> ln 303 suppressing errors with @??
> General doc block returns have got out of sync
> General functions don't have access modifiers
> “Mayden\Pineapple\Util” is never used?

**Comment by i-am-tom** [comment]
- Didn't camelCase everything (not that what was suggested in those code review comments is PascalCase) because some are part of the original PEAR interface. This includes transaction_opcount, which has always been public.
- I don't agree with removing the error suppression if this code has been moved over from PEAR - every change to the original code risks breaking the original interface. Let bad code be bad code.
