### ISSUE TITLE
Should All Methods Not Be Implemented In DriverInterface?

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#32]
Should all methods in `Pineapple\DB\Driver\Common` e.g. `prepare()`, `execute()` be included in the `Pineapple\DB\Driver\DriverInterface`?

I know the drivers are made up of the `DriverInterface` and `Common` however without both you do not have all the methods.

Everywhere you type hint to `DriverInterface` this would mean it would be possible for someone to implement the `DriverInterface` and everything work but they would get an undefined method `prepare()`.

I know there is no plan for this project to be extended beyond the two drivers already, so this might be more of a "nice to have" but it would feel more complete.

There are alternative ways to structure this:

1. Have 3 interfaces
```PHP
interface DriverInterface implements Driver, Common {}
```
Where: `Driver` becomes the current `DriverInterface` and `Common` is an interface for `Pineapple\DB\Driver\Common` and rename `Pineapple\DB\Driver\Common` to something else)

2. Have an abstract and type hint to that
```PHP
abstract class Driver extends Common implements DriverInterface {}
```

There are lots of other solutions as well, just a thought.

**Comment by aphlor** [comment]
Some methods are final (though obvs not marked as such) methods which aren't to be implemented in the driver, and offer features that merely rely on what the `DriverInterface` offers.

I can't quite work out if I should agree or disagree with what you're saying, but I'm inclined to agree because if you expect a `DriverInterface` then the methods in the forced inherited object should exist and conform to an interface, so probably yes.
