### ISSUE TITLE
`getRowCounter()` always returns NULL

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#39]
The `getRowCounter` always returns `NULL`, according to the PEAR [documentation](http://pear.php.net/package/DB/docs/1.9.2/DB/DB_result.html) it should return an integer of "the current row being looked at. Starts at 1.".

**Comment by aphlor** [comment]
Likely a bug in the PDO and Dbal drivers. This tested okay in the test suite, so must have succeeded with the stub driver (see [this test](https://github.com/wethersherbs/pineapple/blob/df95e516ff11a15095d38d7ca498745edbb79f62/test/DB/ResultTest.php#L459)).

**Comment by aphlor** [comment]
I wrote a test for this using PEAR DB. It also doesn't work there.

**Comment by aphlor** [comment]
It seems the only scenario where we can display this working is when the `Result` object is constructed by hand with the product of the `simpleQuery` method, which the `limit_from` and `limit_count` properties set. Since I'm not really all that sure how or if this should work at all, it's too dangerous or pointless to fix. Sorry, but this is a wontfix.
