### ISSUE TITLE
`nextResult()` method not implemented yet

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#41]
The`Pineapple\DB\Driver\Components\PdoCommonMethods` traits `nextResult()` method always returns `false` and is marked with a comment that says: "This method has not been implemented yet."

**Comment by aphlor** [comment]
I was fleeing the building at the time you logged this item and wanted to give immediate feedback, but it should be noted:

a) upstream DB did not implement this for the `mysql` or `mysqli` drivers (hence what you're seeing now is exactly what came from upstream, it is _not_ a driver omission, the PDO driver is feature complete in comparison to the older `mysql` and `mysqli` drivers). See [the original source for the `mysql` driver](https://github.com/pear/DB/blob/trunk/DB/mysql.php#L338).

b) It cannot be supported on MySQL because it supports neither multiple queries in a single execution nor multiple result cursors per execution (think: running a stored procedure which returns two.

As such, thank you for the notification, but closing as this is not required for MySQL use. Can reopen in future if this is required for a proper database.
