### ISSUE TITLE
Util::ThrowError

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#42]
Is this something that has come from PEAR?

Anything with "Throw" in i assume relates to exceptions however is just a wrapper around RaiseError and returns an error object not an exception.

If this just came from PEAR then fine, leave it as is. However if its something @borb has added could it have a different name... basically anything to make it look like its not related to exceptions in any way?

**Comment by Tohmua** [comment]
Spoke to @borb this is from PEAR and PHP4 where there were no Exceptions.

**Comment by aphlor** [comment]
This is a method from PEAR. PHP 4 lacked exceptions so `throwError`, `raiseError`, `isError` were ways of passing errors back as results. Since there was no exception mechanism, these had to be checked by hand. See [the old code](https://github.com/pear/pear-core-minimal/blob/master/src/PEAR.php#L583) for details.
